baseURL = "https://www.virtualmicropolis.com"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
title = "Virtual Micropolis"
# themesDir = "../.."

DefaultContentLanguage = "en" 
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
SectionPagesMenu = "main" 
# googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[params]
description = "A collection of modules built to the TwinLUG Micropolis specification."
favicon = ""
site_logo = "images/logo.png"
#   facebook = ""
#   twitter = "https://twitter.com/GoHugoIO"
#   instagram = ""
#   youtube = ""
github = ""
#   gitlab = ""
#   linkedin = ""
#   mastodon = ""
#   slack = ""
#   stackoverflow = ""
rss = ""
# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-green"
featured_image = "/images/start.jpg"
recent_posts_number = 10
